---
version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-volume:/data/db

  mongoclient:
    image: mongoclient/mongoclient:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3300:3000"